<!DOCTYPE html>
<!-- DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py. -->
<title>Canvas test: 2d.layer.valid-calls.beginLayer-endLayer</title>
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
<script src="/html/canvas/resources/canvas-tests.js"></script>
<link rel="stylesheet" href="/html/canvas/resources/canvas-tests.css">
<body class="show_output">

<h1>2d.layer.valid-calls.beginLayer-endLayer</h1>
<p class="desc">No exception raised on beginLayer() + endLayer().</p>


<p class="output">Actual output:</p>
<canvas id="c" class="output" width="100" height="50"><p class="fallback">FAIL (fallback content)</p></canvas>

<ul id="d"></ul>
<script>
var t = async_test("No exception raised on beginLayer() + endLayer().");
_addTest(function(canvas, ctx) {

  ctx.beginLayer();
  ctx.save();

});
</script>

